services:
  api:
    build:
      context: ./back-end
      dockerfile: VotingSystem.API/Dockerfile
    container_name: voting_api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=voting_pgsql;Database=voting_db;Username=voting_user;Password=voting_pass"
      RabbitMQ__HostName: "voting_rabbitmq"
      RabbitMQ__UserName: "voting_user"
      RabbitMQ__Password: "voting_pass"

  worker:
    build:
      context: ./back-end
      dockerfile: VotingSystem.Worker/Dockerfile
    container_name: voting_worker
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=voting_pgsql;Database=voting_db;Username=voting_user;Password=voting_pass"
      RabbitMQ__HostName: "voting_rabbitmq"
      RabbitMQ__UserName: "voting_user"
      RabbitMQ__Password: "voting_pass"

networks:
  voting_network:
    external: true
