services:
  postgres:
    image: postgres:15
    container_name: voting_pgsql
    restart: always
    environment:
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_pass
      POSTGRES_DB: voting_db
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
