services:
  postgres:
    image: postgres:15
    container_name: voting_pgsql
    restart: always
    environment:
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_pass
      POSTGRES_DB: voting_db
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: voting_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: voting_user
      RABBITMQ_DEFAULT_PASS: voting_pass
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmqdata:

networks:
  voting_network:
    external: true
